{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-1.0.aar",
          "url": "device_info_plus_release-1.0.aar",
          "size": 9562,
          "sha512": "4b0e7ec7a5993b4ec3574c804b8b17b675139643a9df7147370f11b6746e376cc6d41c52cd9ddbf5c0ff2030b92be90e597461c68b6cc568548f4f422cacd875",
          "sha256": "0843c36b49907cae6565b3edc501b45329744d2b693c8d3dc674dddfdcffe4fe",
          "sha1": "e0f981adf8d8874b2cedf68095902aade1fbdf21",
          "md5": "0a5c205bde9ca59b1b24cdfad789869e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-1.0.aar",
          "url": "device_info_plus_release-1.0.aar",
          "size": 9562,
          "sha512": "4b0e7ec7a5993b4ec3574c804b8b17b675139643a9df7147370f11b6746e376cc6d41c52cd9ddbf5c0ff2030b92be90e597461c68b6cc568548f4f422cacd875",
          "sha256": "0843c36b49907cae6565b3edc501b45329744d2b693c8d3dc674dddfdcffe4fe",
          "sha1": "e0f981adf8d8874b2cedf68095902aade1fbdf21",
          "md5": "0a5c205bde9ca59b1b24cdfad789869e"
        }
      ]
    }
  ]
}
