{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-1.0.aar",
          "url": "device_info_plus_release-1.0.aar",
          "size": 9565,
          "sha512": "fdf77d90e2584a54f9748a8103fea027aa80cd564d6a6675db07d7af3e6e9e18ddeab16183edf4c36e12a89c1c55af0cb1297f4ef673ae136f2dcaa0d9f2224f",
          "sha256": "15fd2dab143a7440537fd66d26538e0e1ea784c3b26ce036ac9259eeec47afc2",
          "sha1": "2d0ff74e16c2db052ac4ee83c0933d692ce39d29",
          "md5": "65c8f3eb00b98584cc81db92ac0639e6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-1.0.aar",
          "url": "device_info_plus_release-1.0.aar",
          "size": 9565,
          "sha512": "fdf77d90e2584a54f9748a8103fea027aa80cd564d6a6675db07d7af3e6e9e18ddeab16183edf4c36e12a89c1c55af0cb1297f4ef673ae136f2dcaa0d9f2224f",
          "sha256": "15fd2dab143a7440537fd66d26538e0e1ea784c3b26ce036ac9259eeec47afc2",
          "sha1": "2d0ff74e16c2db052ac4ee83c0933d692ce39d29",
          "md5": "65c8f3eb00b98584cc81db92ac0639e6"
        }
      ]
    }
  ]
}
