{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-1.0.aar",
          "url": "device_info_plus_release-1.0.aar",
          "size": 9469,
          "sha512": "e4346aaccb9984fd10b97d00cef98a96d4f5628009591b9e4cf89f701497427a93d0c196307ebc81e5e60d707661c41aadbde7f05b5432943c66301ff3b787c7",
          "sha256": "7cff8dd590d075629b551ea03be0dc99361752b7fae4914e69aaaa9fd1193e5c",
          "sha1": "acc7886a19de580c08b808ac3389481a4e91e935",
          "md5": "30bcadb7536efe44281fb24e550fddcf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-1.0.aar",
          "url": "device_info_plus_release-1.0.aar",
          "size": 9469,
          "sha512": "e4346aaccb9984fd10b97d00cef98a96d4f5628009591b9e4cf89f701497427a93d0c196307ebc81e5e60d707661c41aadbde7f05b5432943c66301ff3b787c7",
          "sha256": "7cff8dd590d075629b551ea03be0dc99361752b7fae4914e69aaaa9fd1193e5c",
          "sha1": "acc7886a19de580c08b808ac3389481a4e91e935",
          "md5": "30bcadb7536efe44281fb24e550fddcf"
        }
      ]
    }
  ]
}
