{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.videoplayer",
    "module": "video_player_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_profile-1.0.aar",
          "url": "video_player_android_profile-1.0.aar",
          "size": 39722,
          "sha512": "c01d5d096df402a14dcc842a8f8c5cfb41502d16ad6e2896405248d1dfed5ece1ded7bb81f3a885dbf3a43c0ca9ff135d5d3086e117924fb0f8df93aaa1b6624",
          "sha256": "cdbe5b5f9aacc1d24f4c20cfb42be727e480ef372ebcd1f57e8defdda228cefd",
          "sha1": "49782141b9a913bcae8e54d91f7a5055705086f9",
          "md5": "c0bca40a6b202d5d586ddefa66528d19"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.4"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.18.4"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.18.4"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-smoothstreaming",
          "version": {
            "requires": "2.18.4"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_profile-1.0.aar",
          "url": "video_player_android_profile-1.0.aar",
          "size": 39722,
          "sha512": "c01d5d096df402a14dcc842a8f8c5cfb41502d16ad6e2896405248d1dfed5ece1ded7bb81f3a885dbf3a43c0ca9ff135d5d3086e117924fb0f8df93aaa1b6624",
          "sha256": "cdbe5b5f9aacc1d24f4c20cfb42be727e480ef372ebcd1f57e8defdda228cefd",
          "sha1": "49782141b9a913bcae8e54d91f7a5055705086f9",
          "md5": "c0bca40a6b202d5d586ddefa66528d19"
        }
      ]
    }
  ]
}
