{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.videoplayer",
    "module": "video_player_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_profile-1.0.aar",
          "url": "video_player_android_profile-1.0.aar",
          "size": 40156,
          "sha512": "e6131259fc21dbb3d6fde187e6a6a3dc520d885e654bf309b5cb51ffe9e32e73ccd1bc553278d1cf6bdc44b29b3a2072678d5432d8ba0166a72c9ed9db810155",
          "sha256": "56377df606b57690e3d853894d62905824971966a7d4cb6ead5b36db134feda3",
          "sha1": "d37835036921bae1d3cbec9e722fabec39890b3c",
          "md5": "2718f3edc644f95321924df9e0f1d28f"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.4"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.18.4"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.18.4"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-smoothstreaming",
          "version": {
            "requires": "2.18.4"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_profile-1.0.aar",
          "url": "video_player_android_profile-1.0.aar",
          "size": 40156,
          "sha512": "e6131259fc21dbb3d6fde187e6a6a3dc520d885e654bf309b5cb51ffe9e32e73ccd1bc553278d1cf6bdc44b29b3a2072678d5432d8ba0166a72c9ed9db810155",
          "sha256": "56377df606b57690e3d853894d62905824971966a7d4cb6ead5b36db134feda3",
          "sha1": "d37835036921bae1d3cbec9e722fabec39890b3c",
          "md5": "2718f3edc644f95321924df9e0f1d28f"
        }
      ]
    }
  ]
}
