{
  "formatVersion": "1.1",
  "component": {
    "group": "com.advoques.document_file_save_plus",
    "module": "document_file_save_plus_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "document_file_save_plus_release-1.0.aar",
          "url": "document_file_save_plus_release-1.0.aar",
          "size": 7988,
          "sha512": "101da2033645653a075e5bed934be81ad87f58aa5cde591fecaf624cd8890d4c23b41a44664f52f7d2b2fc8de3fdf2382df08e5254944b244e6aa8b26fa60147",
          "sha256": "f0051de8973915c507e85b857dfcc4543d0e8b60cae4d63cce4a3eeef535a3f0",
          "sha1": "521568e7f8939cfa2287ec648d7db8ece69dfdfa",
          "md5": "ff20dd33c94967c7e7661cc3228e287e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "document_file_save_plus_release-1.0.aar",
          "url": "document_file_save_plus_release-1.0.aar",
          "size": 7988,
          "sha512": "101da2033645653a075e5bed934be81ad87f58aa5cde591fecaf624cd8890d4c23b41a44664f52f7d2b2fc8de3fdf2382df08e5254944b244e6aa8b26fa60147",
          "sha256": "f0051de8973915c507e85b857dfcc4543d0e8b60cae4d63cce4a3eeef535a3f0",
          "sha1": "521568e7f8939cfa2287ec648d7db8ece69dfdfa",
          "md5": "ff20dd33c94967c7e7661cc3228e287e"
        }
      ]
    }
  ]
}
