{
  "formatVersion": "1.1",
  "component": {
    "group": "com.advoques.document_file_save_plus",
    "module": "document_file_save_plus_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "document_file_save_plus_release-1.0.aar",
          "url": "document_file_save_plus_release-1.0.aar",
          "size": 7992,
          "sha512": "86941a36f7862e1168dd7172efcda6fc601ce4fe9ced07bd5d0f99b83b212abe4d56f4bf3413ce5d66356dd395129d31f890833d0a3e443c740cba1be1832d6b",
          "sha256": "803eea49c212dfd8316353cf2830550481eba432478608ed38189d8cffae64ed",
          "sha1": "029c2dbd35f52bba3f1122c0068047657d22e1e8",
          "md5": "f2e1c31d7b2973d2837b1c5e559c686f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "document_file_save_plus_release-1.0.aar",
          "url": "document_file_save_plus_release-1.0.aar",
          "size": 7992,
          "sha512": "86941a36f7862e1168dd7172efcda6fc601ce4fe9ced07bd5d0f99b83b212abe4d56f4bf3413ce5d66356dd395129d31f890833d0a3e443c740cba1be1832d6b",
          "sha256": "803eea49c212dfd8316353cf2830550481eba432478608ed38189d8cffae64ed",
          "sha1": "029c2dbd35f52bba3f1122c0068047657d22e1e8",
          "md5": "f2e1c31d7b2973d2837b1c5e559c686f"
        }
      ]
    }
  ]
}
