{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mr.flutter.plugin.filepicker",
    "module": "file_picker_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_release-1.0.aar",
          "url": "file_picker_release-1.0.aar",
          "size": 27513,
          "sha512": "e07cb6d7ce8bd0ab1ece08f28eead3279d973562280ccfcaf8c37c057ebfb968845215a9ec6e27e83ef47242be709b373ddbeee499ce290659776604371804d7",
          "sha256": "659dec4e9bdcdc0539527bd6117cd8827a041f9697f3b6345420f987ee6ffb1e",
          "sha1": "b6873cc51d137189a650b4a55e19f0d227eab0ab",
          "md5": "c593145a6cb99fa8249eaf303a450c9d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_release-1.0.aar",
          "url": "file_picker_release-1.0.aar",
          "size": 27513,
          "sha512": "e07cb6d7ce8bd0ab1ece08f28eead3279d973562280ccfcaf8c37c057ebfb968845215a9ec6e27e83ef47242be709b373ddbeee499ce290659776604371804d7",
          "sha256": "659dec4e9bdcdc0539527bd6117cd8827a041f9697f3b6345420f987ee6ffb1e",
          "sha1": "b6873cc51d137189a650b4a55e19f0d227eab0ab",
          "md5": "c593145a6cb99fa8249eaf303a450c9d"
        }
      ]
    }
  ]
}
