{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mr.flutter.plugin.filepicker",
    "module": "file_picker_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_release-1.0.aar",
          "url": "file_picker_release-1.0.aar",
          "size": 27842,
          "sha512": "878f1d2c2b57693852014ce6cda56b21209bcf0eda739319fb14aa32da859b22dde236807c2a68b87f379a764aabe863933b55cc5192f449fc71e8b06977107d",
          "sha256": "3754e8b4a6223410fce94d2ced4788361964dd20ecfefd95eb332a30a00dbf8f",
          "sha1": "c5204222ffaa6ba99766df9b9ece591701799867",
          "md5": "8f089a83a6e5591fbc9592167ca3387c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_release-1.0.aar",
          "url": "file_picker_release-1.0.aar",
          "size": 27842,
          "sha512": "878f1d2c2b57693852014ce6cda56b21209bcf0eda739319fb14aa32da859b22dde236807c2a68b87f379a764aabe863933b55cc5192f449fc71e8b06977107d",
          "sha256": "3754e8b4a6223410fce94d2ced4788361964dd20ecfefd95eb332a30a00dbf8f",
          "sha1": "c5204222ffaa6ba99766df9b9ece591701799867",
          "md5": "8f089a83a6e5591fbc9592167ca3387c"
        }
      ]
    }
  ]
}
