{
  "formatVersion": "1.1",
  "component": {
    "group": "com.advoques.document_file_save_plus",
    "module": "document_file_save_plus_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        }
      ],
      "files": [
        {
          "name": "document_file_save_plus_profile-1.0.aar",
          "url": "document_file_save_plus_profile-1.0.aar",
          "size": 7909,
          "sha512": "4a2d304961531114a3d8f31b46b1267cdd1ffca1e2c32dda4ed2eb2567f489cd620203c6581ae3efa5cf9e1de1ef83c361ea48037481da82e867d3eb694687a4",
          "sha256": "fe3e4e1ae324bc16bb5d0a27af381e911ab449daaede5f538eb0b09868db34db",
          "sha1": "45a4eee0689c4a1b2b20bf8584a9d2ce4cac8a7f",
          "md5": "648d9813d49eb7559d4f24da2199b6ba"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "document_file_save_plus_profile-1.0.aar",
          "url": "document_file_save_plus_profile-1.0.aar",
          "size": 7909,
          "sha512": "4a2d304961531114a3d8f31b46b1267cdd1ffca1e2c32dda4ed2eb2567f489cd620203c6581ae3efa5cf9e1de1ef83c361ea48037481da82e867d3eb694687a4",
          "sha256": "fe3e4e1ae324bc16bb5d0a27af381e911ab449daaede5f538eb0b09868db34db",
          "sha1": "45a4eee0689c4a1b2b20bf8584a9d2ce4cac8a7f",
          "md5": "648d9813d49eb7559d4f24da2199b6ba"
        }
      ]
    }
  ]
}
