{
  "formatVersion": "1.1",
  "component": {
    "group": "com.advoques.document_file_save_plus",
    "module": "document_file_save_plus_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "document_file_save_plus_profile-1.0.aar",
          "url": "document_file_save_plus_profile-1.0.aar",
          "size": 7982,
          "sha512": "810c1728db469ec23db66a9bb867a2e4bea00278b77d237c76cb5ee6ecb3f44dcde33e6f4de1408bd04764ac803441ae90a5af326993a468f0784e58376d96cd",
          "sha256": "11b269346390b3863cfda1be81718b9ca2af7931aa5e255b62f016a5f24b4534",
          "sha1": "4e464306a401f97bdd1cc67c22722d38dc99a58e",
          "md5": "b7ac37cba29911ac04491df002a6f3d5"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "document_file_save_plus_profile-1.0.aar",
          "url": "document_file_save_plus_profile-1.0.aar",
          "size": 7982,
          "sha512": "810c1728db469ec23db66a9bb867a2e4bea00278b77d237c76cb5ee6ecb3f44dcde33e6f4de1408bd04764ac803441ae90a5af326993a468f0784e58376d96cd",
          "sha256": "11b269346390b3863cfda1be81718b9ca2af7931aa5e255b62f016a5f24b4534",
          "sha1": "4e464306a401f97bdd1cc67c22722d38dc99a58e",
          "md5": "b7ac37cba29911ac04491df002a6f3d5"
        }
      ]
    }
  ]
}
