{
  "formatVersion": "1.1",
  "component": {
    "group": "com.advoques.document_file_save_plus",
    "module": "document_file_save_plus_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "document_file_save_plus_profile-1.0.aar",
          "url": "document_file_save_plus_profile-1.0.aar",
          "size": 7985,
          "sha512": "24e97da32a25a31004fd9c0979f92d1633c245963ed95ff199c59339413832d8a7012d1b81d6de83966e44ad3c398d59d43a990afe3ef8665a1064c38f36ab9c",
          "sha256": "25e413cd6243d4f8f7e47c5856baf17721449f74c191b8ecbf57e643c7795ad2",
          "sha1": "4847cb5926d309b280b75af968722214a84c575b",
          "md5": "4f646ca311edf79f5a439bb35c3796ec"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "document_file_save_plus_profile-1.0.aar",
          "url": "document_file_save_plus_profile-1.0.aar",
          "size": 7985,
          "sha512": "24e97da32a25a31004fd9c0979f92d1633c245963ed95ff199c59339413832d8a7012d1b81d6de83966e44ad3c398d59d43a990afe3ef8665a1064c38f36ab9c",
          "sha256": "25e413cd6243d4f8f7e47c5856baf17721449f74c191b8ecbf57e643c7795ad2",
          "sha1": "4847cb5926d309b280b75af968722214a84c575b",
          "md5": "4f646ca311edf79f5a439bb35c3796ec"
        }
      ]
    }
  ]
}
