{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.geolocator",
    "module": "geolocator_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "geolocator_android_debug-1.0.aar",
          "url": "geolocator_android_debug-1.0.aar",
          "size": 61425,
          "sha512": "66aa04761a3d4d484370ec0f3f3fe69a97273f56653f2fb9b6ee3fa672cd9e9e3c9980258b6cafedf1adf227aefdc7d9f5bab48764da05e0b35061f30cc871da",
          "sha256": "9935c80055cf29f58ab8d074d7793b5457898665c068431a12ab07da27d63702",
          "sha1": "aba69009142ce1c93da1fb59d0a2112d02c29c67",
          "md5": "96798b5a6f0399c76b2e2cd7c91e73cb"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "geolocator_android_debug-1.0.aar",
          "url": "geolocator_android_debug-1.0.aar",
          "size": 61425,
          "sha512": "66aa04761a3d4d484370ec0f3f3fe69a97273f56653f2fb9b6ee3fa672cd9e9e3c9980258b6cafedf1adf227aefdc7d9f5bab48764da05e0b35061f30cc871da",
          "sha256": "9935c80055cf29f58ab8d074d7793b5457898665c068431a12ab07da27d63702",
          "sha1": "aba69009142ce1c93da1fb59d0a2112d02c29c67",
          "md5": "96798b5a6f0399c76b2e2cd7c91e73cb"
        }
      ]
    }
  ]
}
