{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.geolocator",
    "module": "geolocator_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        }
      ],
      "files": [
        {
          "name": "geolocator_android_debug-1.0.aar",
          "url": "geolocator_android_debug-1.0.aar",
          "size": 60672,
          "sha512": "094cb4e61c2b907015cdf676285ed344b8dbbe99481b31b912b0d29eabbb2ac043161f0c559bd2ae195aec85b593ba237e83c38a1143d19ebb10fd20a0aa777d",
          "sha256": "8545e5acb19d64b9c79d1033f4dea232e1605c023f15a93bdf336fd6808cb536",
          "sha1": "b3e3e0823c8540f2cbe6f2a7464a5efee6fad5a5",
          "md5": "03afa6650e3d1193907de48224d487e7"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "geolocator_android_debug-1.0.aar",
          "url": "geolocator_android_debug-1.0.aar",
          "size": 60672,
          "sha512": "094cb4e61c2b907015cdf676285ed344b8dbbe99481b31b912b0d29eabbb2ac043161f0c559bd2ae195aec85b593ba237e83c38a1143d19ebb10fd20a0aa777d",
          "sha256": "8545e5acb19d64b9c79d1033f4dea232e1605c023f15a93bdf336fd6808cb536",
          "sha1": "b3e3e0823c8540f2cbe6f2a7464a5efee6fad5a5",
          "md5": "03afa6650e3d1193907de48224d487e7"
        }
      ]
    }
  ]
}
