{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mr.flutter.plugin.filepicker",
    "module": "file_picker_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_debug-1.0.aar",
          "url": "file_picker_debug-1.0.aar",
          "size": 28701,
          "sha512": "e7de9421451416beb5d514523ddca2d47b5131b46e304092495c356bc66cd3bc726478312c988c3ca8e8c4fb5eb634da7b01072deab8614d6e94decf4d5c8e7f",
          "sha256": "fdfe6cb20c037b8d53bfd90aaed5f127939bf04accf46eef49082d252e3d31c4",
          "sha1": "aa8859b50cb3be04f854d749c2ba9cad72f9b33e",
          "md5": "472cf20bc468a962682c9a80ad37ee0a"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_debug-1.0.aar",
          "url": "file_picker_debug-1.0.aar",
          "size": 28701,
          "sha512": "e7de9421451416beb5d514523ddca2d47b5131b46e304092495c356bc66cd3bc726478312c988c3ca8e8c4fb5eb634da7b01072deab8614d6e94decf4d5c8e7f",
          "sha256": "fdfe6cb20c037b8d53bfd90aaed5f127939bf04accf46eef49082d252e3d31c4",
          "sha1": "aa8859b50cb3be04f854d749c2ba9cad72f9b33e",
          "md5": "472cf20bc468a962682c9a80ad37ee0a"
        }
      ]
    }
  ]
}
