{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mr.flutter.plugin.filepicker",
    "module": "file_picker_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_debug-1.0.aar",
          "url": "file_picker_debug-1.0.aar",
          "size": 29099,
          "sha512": "a1fc59ea8450141aae6d2b08277acf112aa657e3ed74e5dcb78545bc21711817bd5ada423dba16ccfd3c317f8910fad7ef921a8a60b99cc4521a7756bcf638fc",
          "sha256": "e484c929219748b996779740aceff10046da304989b0c0b61b403b7f68e1652e",
          "sha1": "a2c57ea5845004a19574f8fb37688e80b2252df0",
          "md5": "48e4826331b06e29aa43ce9f41eed4f6"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_debug-1.0.aar",
          "url": "file_picker_debug-1.0.aar",
          "size": 29099,
          "sha512": "a1fc59ea8450141aae6d2b08277acf112aa657e3ed74e5dcb78545bc21711817bd5ada423dba16ccfd3c317f8910fad7ef921a8a60b99cc4521a7756bcf638fc",
          "sha256": "e484c929219748b996779740aceff10046da304989b0c0b61b403b7f68e1652e",
          "sha1": "a2c57ea5845004a19574f8fb37688e80b2252df0",
          "md5": "48e4826331b06e29aa43ce9f41eed4f6"
        }
      ]
    }
  ]
}
