{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_debug-1.0.aar",
          "url": "device_info_plus_debug-1.0.aar",
          "size": 9883,
          "sha512": "123d7fbf439f959e21991acc1164cda5b044509c79d8c025309058844e1c125764e9d1356832204a902922221bb7a036f0befd61be5144629a5a9f0364e2a598",
          "sha256": "760c546df9db70c7140b98ed82434643650c50f62ed36ae82fa0985e63f92668",
          "sha1": "ad1db40bd781be88cd2cdd09f16294f3e1a66815",
          "md5": "e4abad7875ebb9f8a53f2406978aac16"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_debug-1.0.aar",
          "url": "device_info_plus_debug-1.0.aar",
          "size": 9883,
          "sha512": "123d7fbf439f959e21991acc1164cda5b044509c79d8c025309058844e1c125764e9d1356832204a902922221bb7a036f0befd61be5144629a5a9f0364e2a598",
          "sha256": "760c546df9db70c7140b98ed82434643650c50f62ed36ae82fa0985e63f92668",
          "sha1": "ad1db40bd781be88cd2cdd09f16294f3e1a66815",
          "md5": "e4abad7875ebb9f8a53f2406978aac16"
        }
      ]
    }
  ]
}
