{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_debug-1.0.aar",
          "url": "device_info_plus_debug-1.0.aar",
          "size": 9878,
          "sha512": "5ab9737ffd164bb9b3ddd0403593ff005a1574f3d83404fa564a1db1ae7b7274a43d8275baf4ecf580317adab2d60e940e17d408ecde250a02edf2116493d584",
          "sha256": "bb3d08ffb5a2227bb61c0bf65323c185f3334546e6d4017c58fa3d4dd8325fcf",
          "sha1": "316e2d52cb3a16d1e4d376e06e34e54806512c92",
          "md5": "03a329aa8b815d81c7838206139084b4"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_debug-1.0.aar",
          "url": "device_info_plus_debug-1.0.aar",
          "size": 9878,
          "sha512": "5ab9737ffd164bb9b3ddd0403593ff005a1574f3d83404fa564a1db1ae7b7274a43d8275baf4ecf580317adab2d60e940e17d408ecde250a02edf2116493d584",
          "sha256": "bb3d08ffb5a2227bb61c0bf65323c185f3334546e6d4017c58fa3d4dd8325fcf",
          "sha1": "316e2d52cb3a16d1e4d376e06e34e54806512c92",
          "md5": "03a329aa8b815d81c7838206139084b4"
        }
      ]
    }
  ]
}
