{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-1.0.aar",
          "url": "permission_handler_android_release-1.0.aar",
          "size": 25092,
          "sha512": "05a82b0d6750fbdbed71258896d7b589a9b71ed93d0e2f85893897d337b01e1d02426de680263e9cb969548d5ff03d16ca7f715f48d1f00684fbc93528c78c49",
          "sha256": "91a17e2661fb38aaccb3bbe62883765d0b41ed64870cb3f45cadd359276fbe35",
          "sha1": "5751700855ce5f6796c9ccc32820f9a05ff4b86d",
          "md5": "81be4507bb06adf312144ef62feaa897"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-1.0.aar",
          "url": "permission_handler_android_release-1.0.aar",
          "size": 25092,
          "sha512": "05a82b0d6750fbdbed71258896d7b589a9b71ed93d0e2f85893897d337b01e1d02426de680263e9cb969548d5ff03d16ca7f715f48d1f00684fbc93528c78c49",
          "sha256": "91a17e2661fb38aaccb3bbe62883765d0b41ed64870cb3f45cadd359276fbe35",
          "sha1": "5751700855ce5f6796c9ccc32820f9a05ff4b86d",
          "md5": "81be4507bb06adf312144ef62feaa897"
        }
      ]
    }
  ]
}
