{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-1.0.aar",
          "url": "permission_handler_android_release-1.0.aar",
          "size": 25298,
          "sha512": "f8382368a27cd1d79eacdcd21085ebe9bc2e184de8be25edb4ef9e877dbfdd68e4e408475462a6fdd975826005e7b506ab009bcfe7205d061421621bdfd1a195",
          "sha256": "6f0a81bb252b4ac69574f3f8b0864e006051b573fd3ff069936c696565f78731",
          "sha1": "8cd92a143b7d417420bfef8cdc90964f364d61af",
          "md5": "99ba3628880e3be9df019396c395beac"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-1.0.aar",
          "url": "permission_handler_android_release-1.0.aar",
          "size": 25298,
          "sha512": "f8382368a27cd1d79eacdcd21085ebe9bc2e184de8be25edb4ef9e877dbfdd68e4e408475462a6fdd975826005e7b506ab009bcfe7205d061421621bdfd1a195",
          "sha256": "6f0a81bb252b4ac69574f3f8b0864e006051b573fd3ff069936c696565f78731",
          "sha1": "8cd92a143b7d417420bfef8cdc90964f364d61af",
          "md5": "99ba3628880e3be9df019396c395beac"
        }
      ]
    }
  ]
}
