{
  "formatVersion": "1.1",
  "component": {
    "group": "com.crazecoder.openfile",
    "module": "open_filex_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "open_filex_debug-1.0.aar",
          "url": "open_filex_debug-1.0.aar",
          "size": 14298,
          "sha512": "d06c6ed938ec62ba05153885c082ba11f15f07b09089632112657eea17f9c329153f8faa0cf282263e09d461ae6137c9921205c57773f101f92800d379d8e26e",
          "sha256": "bbcdc456a55df69c76ff3bd9cc49f26094a3ee62e8611f321610ddce096d6f11",
          "sha1": "d5e924a09c32938768fcc46cf433915acb9a8fa6",
          "md5": "ae39a7bdfa6e64a00550c239a1fbd60e"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "open_filex_debug-1.0.aar",
          "url": "open_filex_debug-1.0.aar",
          "size": 14298,
          "sha512": "d06c6ed938ec62ba05153885c082ba11f15f07b09089632112657eea17f9c329153f8faa0cf282263e09d461ae6137c9921205c57773f101f92800d379d8e26e",
          "sha256": "bbcdc456a55df69c76ff3bd9cc49f26094a3ee62e8611f321610ddce096d6f11",
          "sha1": "d5e924a09c32938768fcc46cf433915acb9a8fa6",
          "md5": "ae39a7bdfa6e64a00550c239a1fbd60e"
        }
      ]
    }
  ]
}
