{
  "formatVersion": "1.1",
  "component": {
    "group": "com.crazecoder.openfile",
    "module": "open_filex_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "open_filex_debug-1.0.aar",
          "url": "open_filex_debug-1.0.aar",
          "size": 24292,
          "sha512": "8fc45d578318afab7c1b16a6c933b762e943d368ac683858749b86bf8b6733184db62076f21cd099570c3f88b7d42fa84b25ec5b99bdcc5a488be39975c9c43f",
          "sha256": "9b19c2705fe200424e76e0aff2dec5512c28f3f608d6bb55463d6e7d4815a0c6",
          "sha1": "f40c2c35ddb583f8f0fb3c52702e8565c9034552",
          "md5": "28c606044dac357a9e30cdf0c90aa45a"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "open_filex_debug-1.0.aar",
          "url": "open_filex_debug-1.0.aar",
          "size": 24292,
          "sha512": "8fc45d578318afab7c1b16a6c933b762e943d368ac683858749b86bf8b6733184db62076f21cd099570c3f88b7d42fa84b25ec5b99bdcc5a488be39975c9c43f",
          "sha256": "9b19c2705fe200424e76e0aff2dec5512c28f3f608d6bb55463d6e7d4815a0c6",
          "sha1": "f40c2c35ddb583f8f0fb3c52702e8565c9034552",
          "md5": "28c606044dac357a9e30cdf0c90aa45a"
        }
      ]
    }
  ]
}
