{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_release-1.0.aar",
          "url": "path_provider_android_release-1.0.aar",
          "size": 12590,
          "sha512": "8401f0dd7cb4e5e2540cfb59f680a082ffcb0ca8a93e02939be3e78a2c87e60c9574cf22cb370b13ed1ab26b4ef6ec9654f7bc1f6ea0d0d23b49c5cd39c3d3c0",
          "sha256": "41e2fce5ea9c42cdc1fda34385ce8bb34d0a57d380dde0119b7a544dd1d01ded",
          "sha1": "29850c882106d8abebdab9d13e6d167470ee412b",
          "md5": "564ea703e185a6071d6fe414ef6903a0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_release-1.0.aar",
          "url": "path_provider_android_release-1.0.aar",
          "size": 12590,
          "sha512": "8401f0dd7cb4e5e2540cfb59f680a082ffcb0ca8a93e02939be3e78a2c87e60c9574cf22cb370b13ed1ab26b4ef6ec9654f7bc1f6ea0d0d23b49c5cd39c3d3c0",
          "sha256": "41e2fce5ea9c42cdc1fda34385ce8bb34d0a57d380dde0119b7a544dd1d01ded",
          "sha1": "29850c882106d8abebdab9d13e6d167470ee412b",
          "md5": "564ea703e185a6071d6fe414ef6903a0"
        }
      ]
    }
  ]
}
