{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.geolocator",
    "module": "geolocator_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "geolocator_android_profile-1.0.aar",
          "url": "geolocator_android_profile-1.0.aar",
          "size": 58464,
          "sha512": "4587cdde116f1dc08fdeecd7d5e4843d711957872edc1173c4491407684131b3f4a730e73d6ddeb1ac0bda0a0660d48409c50a21d1ad5e66795ac1ddbc60dd28",
          "sha256": "5d8d5efb2aecef5cc36658a37684638a4e2a759858479844059b9eea2bb3a6d9",
          "sha1": "381757b684b27e0a6fc2855a9ad1a6674069e31e",
          "md5": "02e78e3680ffa26afb0fb475a7df240d"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "geolocator_android_profile-1.0.aar",
          "url": "geolocator_android_profile-1.0.aar",
          "size": 58464,
          "sha512": "4587cdde116f1dc08fdeecd7d5e4843d711957872edc1173c4491407684131b3f4a730e73d6ddeb1ac0bda0a0660d48409c50a21d1ad5e66795ac1ddbc60dd28",
          "sha256": "5d8d5efb2aecef5cc36658a37684638a4e2a759858479844059b9eea2bb3a6d9",
          "sha1": "381757b684b27e0a6fc2855a9ad1a6674069e31e",
          "md5": "02e78e3680ffa26afb0fb475a7df240d"
        }
      ]
    }
  ]
}
