{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_profile-1.0.aar",
          "url": "shared_preferences_android_profile-1.0.aar",
          "size": 10062,
          "sha512": "e0e1b9932a26cd6b9c92cd7c14236095e26c26487a1dea1687aa8f1f04f1ad6e7526c871272c224f0f8487b01c3e2bfecef1c6a2e6ba328f40359ea011a3c774",
          "sha256": "6e5a2586401c08a79aca63178b55e925fabd5426ead645e40f9d228dbb48a542",
          "sha1": "2a94db54066d8ce5f3be03300b3f990e2a511444",
          "md5": "862ad1dc27d13d35d840919a22b4b617"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_profile-1.0.aar",
          "url": "shared_preferences_android_profile-1.0.aar",
          "size": 10062,
          "sha512": "e0e1b9932a26cd6b9c92cd7c14236095e26c26487a1dea1687aa8f1f04f1ad6e7526c871272c224f0f8487b01c3e2bfecef1c6a2e6ba328f40359ea011a3c774",
          "sha256": "6e5a2586401c08a79aca63178b55e925fabd5426ead645e40f9d228dbb48a542",
          "sha1": "2a94db54066d8ce5f3be03300b3f990e2a511444",
          "md5": "862ad1dc27d13d35d840919a22b4b617"
        }
      ]
    }
  ]
}
