{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_profile-1.0.aar",
          "url": "path_provider_android_profile-1.0.aar",
          "size": 12483,
          "sha512": "0426c47319ddd2f7e2fb5f4bfef224d3f19f1dcaea7b18b846cd5bdac297d14762f0556b2c71df8b3daee5f14639db2db714a7ab1d159902c68c03863f275545",
          "sha256": "7bf6eee09c6acbbdd3702181126f018e737cd16d93028c4f4522c44dda50731f",
          "sha1": "9db12707621466caad5a0bd7494cc996276e667c",
          "md5": "7909c53232bfe56e3d294a3edbdc1e98"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_profile-1.0.aar",
          "url": "path_provider_android_profile-1.0.aar",
          "size": 12483,
          "sha512": "0426c47319ddd2f7e2fb5f4bfef224d3f19f1dcaea7b18b846cd5bdac297d14762f0556b2c71df8b3daee5f14639db2db714a7ab1d159902c68c03863f275545",
          "sha256": "7bf6eee09c6acbbdd3702181126f018e737cd16d93028c4f4522c44dda50731f",
          "sha1": "9db12707621466caad5a0bd7494cc996276e667c",
          "md5": "7909c53232bfe56e3d294a3edbdc1e98"
        }
      ]
    }
  ]
}
