{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_profile-1.0.aar",
          "url": "path_provider_android_profile-1.0.aar",
          "size": 12586,
          "sha512": "d21480c754ce7b868faeead1490fe22ca458bcdd807dd9c36cab8abd4c69269cb38ac2e58149ac08c0ca2c7ff49e1a75f109e3318aa48568d7279589ee5b3568",
          "sha256": "447b3fcd003dfb2111793fe9086ae7fda82572b702b8ea5eb33f532243f38734",
          "sha1": "9bdab2a0ca188fd81fa5d49d958fba3fceec7ddb",
          "md5": "5da0874fac106df84639ae4d6e47a167"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_profile-1.0.aar",
          "url": "path_provider_android_profile-1.0.aar",
          "size": 12586,
          "sha512": "d21480c754ce7b868faeead1490fe22ca458bcdd807dd9c36cab8abd4c69269cb38ac2e58149ac08c0ca2c7ff49e1a75f109e3318aa48568d7279589ee5b3568",
          "sha256": "447b3fcd003dfb2111793fe9086ae7fda82572b702b8ea5eb33f532243f38734",
          "sha1": "9bdab2a0ca188fd81fa5d49d958fba3fceec7ddb",
          "md5": "5da0874fac106df84639ae4d6e47a167"
        }
      ]
    }
  ]
}
