{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
    "module": "flutter_plugin_android_lifecycle_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_debug-1.0.aar",
          "url": "flutter_plugin_android_lifecycle_debug-1.0.aar",
          "size": 4942,
          "sha512": "fed1e1318bea0282c7ce7042c2cd21a512b4f657256c4a7bd4386aea1b35dedea0025fa7a7b2f1b8485daf89fccb5429dfbde49e10ac268408ad5917703ba4b1",
          "sha256": "1e6c90a7bf47d45a6f0605059e0dbba5784bfbdddd37fb13a83cc2c4e5d29122",
          "sha1": "29aaf78903b4e9338a75ebd5d2e68eee2facf3c4",
          "md5": "382f5e007545ac450c28945a14135a68"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_debug-1.0.aar",
          "url": "flutter_plugin_android_lifecycle_debug-1.0.aar",
          "size": 4942,
          "sha512": "fed1e1318bea0282c7ce7042c2cd21a512b4f657256c4a7bd4386aea1b35dedea0025fa7a7b2f1b8485daf89fccb5429dfbde49e10ac268408ad5917703ba4b1",
          "sha256": "1e6c90a7bf47d45a6f0605059e0dbba5784bfbdddd37fb13a83cc2c4e5d29122",
          "sha1": "29aaf78903b4e9338a75ebd5d2e68eee2facf3c4",
          "md5": "382f5e007545ac450c28945a14135a68"
        }
      ]
    }
  ]
}
