{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_debug-1.0.aar",
          "url": "path_provider_android_debug-1.0.aar",
          "size": 13119,
          "sha512": "5758bce891e9b948621b569d6af4c918bd15d015b0d6cbf4f69312dad3ca86d0d665d6a989f28c8eb512ccc05b0c063b2b56989380dcf39ae1552893f1c2e8df",
          "sha256": "6694439f39bdbf8561ff9a85b62112c9e1c3208eaa231d2086db5e35d2638b11",
          "sha1": "282b7be092451474abfc8414b4fcafd84e47dbf5",
          "md5": "8a9249c54d6650543177d691e97de575"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_debug-1.0.aar",
          "url": "path_provider_android_debug-1.0.aar",
          "size": 13119,
          "sha512": "5758bce891e9b948621b569d6af4c918bd15d015b0d6cbf4f69312dad3ca86d0d665d6a989f28c8eb512ccc05b0c063b2b56989380dcf39ae1552893f1c2e8df",
          "sha256": "6694439f39bdbf8561ff9a85b62112c9e1c3208eaa231d2086db5e35d2638b11",
          "sha1": "282b7be092451474abfc8414b4fcafd84e47dbf5",
          "md5": "8a9249c54d6650543177d691e97de575"
        }
      ]
    }
  ]
}
