{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_debug-1.0.aar",
          "url": "path_provider_android_debug-1.0.aar",
          "size": 13062,
          "sha512": "f19371c850e30eba9870ead92e5d2a0129452df3f755ad15a4505328d7cb6a2ac9206ee1e35f1dcde52910fc7bdce128213568b1b1c9f526208b0564cae1d7c0",
          "sha256": "1c68773956ab1fd38d3218faa99fe01bfac65ab188b82138fc322b2734e37890",
          "sha1": "3842423feb4507e742063bb32a5916c3051849f5",
          "md5": "d8267408d33c7563ae646b0a09a698c2"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_debug-1.0.aar",
          "url": "path_provider_android_debug-1.0.aar",
          "size": 13062,
          "sha512": "f19371c850e30eba9870ead92e5d2a0129452df3f755ad15a4505328d7cb6a2ac9206ee1e35f1dcde52910fc7bdce128213568b1b1c9f526208b0564cae1d7c0",
          "sha256": "1c68773956ab1fd38d3218faa99fe01bfac65ab188b82138fc322b2734e37890",
          "sha1": "3842423feb4507e742063bb32a5916c3051849f5",
          "md5": "d8267408d33c7563ae646b0a09a698c2"
        }
      ]
    }
  ]
}
