{
  "formatVersion": "1.1",
  "component": {
    "group": "com.crazecoder.openfile",
    "module": "open_filex_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "open_filex_profile-1.0.aar",
          "url": "open_filex_profile-1.0.aar",
          "size": 13767,
          "sha512": "ec1caa1148355cd65c956076a60f85f6da65c01990d070a87166356b23130c8be6a8eb5c82116ef32a2d7783cf93ddac4c5568876c1e7c69b76cd36c82b2c701",
          "sha256": "b88d07be57400ec6ee10b246964f6707c4657fa4435c644719cc97517585f3c6",
          "sha1": "acb28d86577ea3c8d276af4ad1425ad5a1a58c33",
          "md5": "7d8985d7d0996cb5f25587b60a9d576a"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "open_filex_profile-1.0.aar",
          "url": "open_filex_profile-1.0.aar",
          "size": 13767,
          "sha512": "ec1caa1148355cd65c956076a60f85f6da65c01990d070a87166356b23130c8be6a8eb5c82116ef32a2d7783cf93ddac4c5568876c1e7c69b76cd36c82b2c701",
          "sha256": "b88d07be57400ec6ee10b246964f6707c4657fa4435c644719cc97517585f3c6",
          "sha1": "acb28d86577ea3c8d276af4ad1425ad5a1a58c33",
          "md5": "7d8985d7d0996cb5f25587b60a9d576a"
        }
      ]
    }
  ]
}
