{
  "formatVersion": "1.1",
  "component": {
    "group": "com.crazecoder.openfile",
    "module": "open_filex_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "open_filex_profile-1.0.aar",
          "url": "open_filex_profile-1.0.aar",
          "size": 13709,
          "sha512": "f306dc30271bb2ce116442648bc1bbb3ca577271831611ec1998ea95fb7517319865b51585520d2533962b73e5fb838a9f77db7194fafacc37451e0876aef773",
          "sha256": "078b9d0aee7740afb2026589793ee5cc5e7d2647f3c7bc5e87e1edf2300474ab",
          "sha1": "e2aa42dd76d3e261167450255e197a6606f7b40f",
          "md5": "faa57794b2008d404e185f2174b17329"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "open_filex_profile-1.0.aar",
          "url": "open_filex_profile-1.0.aar",
          "size": 13709,
          "sha512": "f306dc30271bb2ce116442648bc1bbb3ca577271831611ec1998ea95fb7517319865b51585520d2533962b73e5fb838a9f77db7194fafacc37451e0876aef773",
          "sha256": "078b9d0aee7740afb2026589793ee5cc5e7d2647f3c7bc5e87e1edf2300474ab",
          "sha1": "e2aa42dd76d3e261167450255e197a6606f7b40f",
          "md5": "faa57794b2008d404e185f2174b17329"
        }
      ]
    }
  ]
}
