{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
    "module": "flutter_plugin_android_lifecycle_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_profile-1.0.aar",
          "url": "flutter_plugin_android_lifecycle_profile-1.0.aar",
          "size": 4802,
          "sha512": "60e360d2fe610b9926ef6f1c0eb12b15c375f1df8bf3e4ec96383943f0847ceed682b89f404af6c92480a62a9d9760f29ca5704f4e86372af41b1e846a1557c4",
          "sha256": "652c532a8f2df1e579b5354cac72a5c3e376077630c06e15221a7e85a155df6d",
          "sha1": "2a25afc2d11f5f877fc0849b8adda5f0fc1bc25c",
          "md5": "abaa0bf09d7d3f52623c4578a8511083"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_profile-1.0.aar",
          "url": "flutter_plugin_android_lifecycle_profile-1.0.aar",
          "size": 4802,
          "sha512": "60e360d2fe610b9926ef6f1c0eb12b15c375f1df8bf3e4ec96383943f0847ceed682b89f404af6c92480a62a9d9760f29ca5704f4e86372af41b1e846a1557c4",
          "sha256": "652c532a8f2df1e579b5354cac72a5c3e376077630c06e15221a7e85a155df6d",
          "sha1": "2a25afc2d11f5f877fc0849b8adda5f0fc1bc25c",
          "md5": "abaa0bf09d7d3f52623c4578a8511083"
        }
      ]
    }
  ]
}
