{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
    "module": "flutter_plugin_android_lifecycle_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_profile-1.0.aar",
          "url": "flutter_plugin_android_lifecycle_profile-1.0.aar",
          "size": 4800,
          "sha512": "b6bf877b053838741315d10cbd4a3d5699eb10ffa15055702d98f34ef4a347a7b44611924ff201dce2dc40445ac827c97367950fe58890ce0c032c0fdaff65d7",
          "sha256": "9cad6a9ee8db7ae33e048f627c9b4f69248d8727bf1c18d3d48b939056af4b0e",
          "sha1": "64e4653c989ee24cf25f8ba269f28884fb9bcfdc",
          "md5": "51a227164c0e574fd75af3db0845dee7"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_profile-1.0.aar",
          "url": "flutter_plugin_android_lifecycle_profile-1.0.aar",
          "size": 4800,
          "sha512": "b6bf877b053838741315d10cbd4a3d5699eb10ffa15055702d98f34ef4a347a7b44611924ff201dce2dc40445ac827c97367950fe58890ce0c032c0fdaff65d7",
          "sha256": "9cad6a9ee8db7ae33e048f627c9b4f69248d8727bf1c18d3d48b939056af4b0e",
          "sha1": "64e4653c989ee24cf25f8ba269f28884fb9bcfdc",
          "md5": "51a227164c0e574fd75af3db0845dee7"
        }
      ]
    }
  ]
}
