{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.geolocator",
    "module": "geolocator_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        }
      ],
      "files": [
        {
          "name": "geolocator_android_release-1.0.aar",
          "url": "geolocator_android_release-1.0.aar",
          "size": 57577,
          "sha512": "1500988cc7acd962093bb8549be73f28d9c6d9c148011926ba1a9e0038519bdd48a00228622db0a68756b74983b78d51c44e7e85226f79dbcf8d5445fd9253fd",
          "sha256": "8358dc8ffdb6bf4377bdac778e33bdbadc6728c9e580b379a666f312ba697667",
          "sha1": "8c388c748555204223863f71b4bc3994677165d4",
          "md5": "ed85424085399ff277e9f92d050bd7d4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "geolocator_android_release-1.0.aar",
          "url": "geolocator_android_release-1.0.aar",
          "size": 57577,
          "sha512": "1500988cc7acd962093bb8549be73f28d9c6d9c148011926ba1a9e0038519bdd48a00228622db0a68756b74983b78d51c44e7e85226f79dbcf8d5445fd9253fd",
          "sha256": "8358dc8ffdb6bf4377bdac778e33bdbadc6728c9e580b379a666f312ba697667",
          "sha1": "8c388c748555204223863f71b4bc3994677165d4",
          "md5": "ed85424085399ff277e9f92d050bd7d4"
        }
      ]
    }
  ]
}
