{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.geolocator",
    "module": "geolocator_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "geolocator_android_release-1.0.aar",
          "url": "geolocator_android_release-1.0.aar",
          "size": 58462,
          "sha512": "07ee2e33d5ca29673a3a3b397ca55282c3206e1ef3387f4b69a805b724c3217e03545e29299141e1e232e2277ceed47ac6beb62d1b0ca3eacf8c8a22133e8e33",
          "sha256": "ecac04272cdbd4c04e4b2ed1716c7af34d043a778fe4efd17474fc174c8b7b03",
          "sha1": "79df3101604fd7c368f564787c3c1c3837d5e140",
          "md5": "999f9a6af12a4dca6a9ab78c831c5a36"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "geolocator_android_release-1.0.aar",
          "url": "geolocator_android_release-1.0.aar",
          "size": 58462,
          "sha512": "07ee2e33d5ca29673a3a3b397ca55282c3206e1ef3387f4b69a805b724c3217e03545e29299141e1e232e2277ceed47ac6beb62d1b0ca3eacf8c8a22133e8e33",
          "sha256": "ecac04272cdbd4c04e4b2ed1716c7af34d043a778fe4efd17474fc174c8b7b03",
          "sha1": "79df3101604fd7c368f564787c3c1c3837d5e140",
          "md5": "999f9a6af12a4dca6a9ab78c831c5a36"
        }
      ]
    }
  ]
}
