{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.googlemaps",
    "module": "google_maps_flutter_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        }
      ],
      "files": [
        {
          "name": "google_maps_flutter_android_profile-1.0.aar",
          "url": "google_maps_flutter_android_profile-1.0.aar",
          "size": 64620,
          "sha512": "cb8c1354603c01da6c5f838c02fd2ed08dbc0549eb91f351c3556548d6c2c41dd39a818373fee220b7b53533f9a577943208e34dbb04ca49a0609ef1aee552cf",
          "sha256": "d2467a09dabc0a4351474ebd2d7ce4ff825423070236a3683908aca6c0eebc1e",
          "sha1": "78d3b4d778a93ff177b3cd802471ca7dbd51d6a8",
          "md5": "b96b0b33a8b8ceb6829616275b966f52"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "google_maps_flutter_android_profile-1.0.aar",
          "url": "google_maps_flutter_android_profile-1.0.aar",
          "size": 64620,
          "sha512": "cb8c1354603c01da6c5f838c02fd2ed08dbc0549eb91f351c3556548d6c2c41dd39a818373fee220b7b53533f9a577943208e34dbb04ca49a0609ef1aee552cf",
          "sha256": "d2467a09dabc0a4351474ebd2d7ce4ff825423070236a3683908aca6c0eebc1e",
          "sha1": "78d3b4d778a93ff177b3cd802471ca7dbd51d6a8",
          "md5": "b96b0b33a8b8ceb6829616275b966f52"
        }
      ]
    }
  ]
}
