{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_debug-1.0.aar",
          "url": "shared_preferences_android_debug-1.0.aar",
          "size": 10613,
          "sha512": "06375054979a408f95763aaff4e38324ee79edd5f2e3fee521bdd38a382064ad8a1185466b69c22a727d3844e8ce97541278ac07676a73d01b70002999fde4a7",
          "sha256": "d28c0a1c95e59ea14993662a6fa2570d034127cafba4f5076396f3e2def190c6",
          "sha1": "9fb020b179ca59c0ccc5326b1b7f6c524de9c1e0",
          "md5": "e1903e5ed189be8d94efdd37f0447ec0"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_debug-1.0.aar",
          "url": "shared_preferences_android_debug-1.0.aar",
          "size": 10613,
          "sha512": "06375054979a408f95763aaff4e38324ee79edd5f2e3fee521bdd38a382064ad8a1185466b69c22a727d3844e8ce97541278ac07676a73d01b70002999fde4a7",
          "sha256": "d28c0a1c95e59ea14993662a6fa2570d034127cafba4f5076396f3e2def190c6",
          "sha1": "9fb020b179ca59c0ccc5326b1b7f6c524de9c1e0",
          "md5": "e1903e5ed189be8d94efdd37f0447ec0"
        }
      ]
    }
  ]
}
