{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_debug-1.0.aar",
          "url": "permission_handler_android_debug-1.0.aar",
          "size": 26382,
          "sha512": "0979ccf49da067128341553fd219cf98cc2284109790a460f9767d96cce085a901232a9180f53ee21dcae61a0fa8437ebb88dbb256373fc8b6218426fa9390af",
          "sha256": "c2252a594d7fd274149179c090f26f9662c8d83ad742fdc2e5adf780289a14e2",
          "sha1": "3f48f94990a1335ffa42f671676ee4b5c7e5878d",
          "md5": "d93183ca8976a7a71de0b5cb6abae5af"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_debug-1.0.aar",
          "url": "permission_handler_android_debug-1.0.aar",
          "size": 26382,
          "sha512": "0979ccf49da067128341553fd219cf98cc2284109790a460f9767d96cce085a901232a9180f53ee21dcae61a0fa8437ebb88dbb256373fc8b6218426fa9390af",
          "sha256": "c2252a594d7fd274149179c090f26f9662c8d83ad742fdc2e5adf780289a14e2",
          "sha1": "3f48f94990a1335ffa42f671676ee4b5c7e5878d",
          "md5": "d93183ca8976a7a71de0b5cb6abae5af"
        }
      ]
    }
  ]
}
