{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_debug-1.0.aar",
          "url": "permission_handler_android_debug-1.0.aar",
          "size": 26208,
          "sha512": "bbda181397920538400ef254d16eaed5eeeb3d938c686889b5317964660ac953d9596b08407c534c0d5c45d66af7103cf5e27aee51640521735963683e2307d5",
          "sha256": "145091b084951fbeb2cef1b09de51d8e1f784ea9f260d1832c1e4c4c281452cf",
          "sha1": "9a6d89011d63c22623633a977fe1bc28b04b0abd",
          "md5": "29b88e293631986b7ede2f13dc517608"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_debug-1.0.aar",
          "url": "permission_handler_android_debug-1.0.aar",
          "size": 26208,
          "sha512": "bbda181397920538400ef254d16eaed5eeeb3d938c686889b5317964660ac953d9596b08407c534c0d5c45d66af7103cf5e27aee51640521735963683e2307d5",
          "sha256": "145091b084951fbeb2cef1b09de51d8e1f784ea9f260d1832c1e4c4c281452cf",
          "sha1": "9a6d89011d63c22623633a977fe1bc28b04b0abd",
          "md5": "29b88e293631986b7ede2f13dc517608"
        }
      ]
    }
  ]
}
