{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
    "module": "flutter_plugin_android_lifecycle_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-1.0.aar",
          "url": "flutter_plugin_android_lifecycle_release-1.0.aar",
          "size": 4806,
          "sha512": "f2a4183510ed270ddc0ed95e934cfe58e5aa9b1c2ef8e0335f0f309d6086c0acd39431d6103f4f461ddbab08896d2d0d79ff42d96b06bde8092e470e8c12f241",
          "sha256": "3ed68957bdb8baac552c7940218dfce5a8794058474ef283ea4af92a6968073d",
          "sha1": "e9f96263b27af41617ce0109168279275df53009",
          "md5": "93c9cc2b1232b8564d87d39395951f5c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_release-1.0.aar",
          "url": "flutter_plugin_android_lifecycle_release-1.0.aar",
          "size": 4806,
          "sha512": "f2a4183510ed270ddc0ed95e934cfe58e5aa9b1c2ef8e0335f0f309d6086c0acd39431d6103f4f461ddbab08896d2d0d79ff42d96b06bde8092e470e8c12f241",
          "sha256": "3ed68957bdb8baac552c7940218dfce5a8794058474ef283ea4af92a6968073d",
          "sha1": "e9f96263b27af41617ce0109168279275df53009",
          "md5": "93c9cc2b1232b8564d87d39395951f5c"
        }
      ]
    }
  ]
}
