{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.googlemaps",
    "module": "google_maps_flutter_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        }
      ],
      "files": [
        {
          "name": "google_maps_flutter_android_release-1.0.aar",
          "url": "google_maps_flutter_android_release-1.0.aar",
          "size": 64622,
          "sha512": "9ca2d3bbf127285213684d73e55fcf1e5a46f6287237ddbdced8a780904942e44538c52c87900568c279b85b2446e4ce8cebe5a022330bb0b74ee59a1e8cb467",
          "sha256": "a095ad36c0ef726ffa066b6ce9c8cfaa2decf5c01cccf510d77e8dbca6f2e6f2",
          "sha1": "068d7c5a401c58efe1226242830af2088856b91d",
          "md5": "57980cdee9d9faf6d8330df0dfd7e845"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "google_maps_flutter_android_release-1.0.aar",
          "url": "google_maps_flutter_android_release-1.0.aar",
          "size": 64622,
          "sha512": "9ca2d3bbf127285213684d73e55fcf1e5a46f6287237ddbdced8a780904942e44538c52c87900568c279b85b2446e4ce8cebe5a022330bb0b74ee59a1e8cb467",
          "sha256": "a095ad36c0ef726ffa066b6ce9c8cfaa2decf5c01cccf510d77e8dbca6f2e6f2",
          "sha1": "068d7c5a401c58efe1226242830af2088856b91d",
          "md5": "57980cdee9d9faf6d8330df0dfd7e845"
        }
      ]
    }
  ]
}
