{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_profile-1.0.aar",
          "url": "device_info_plus_profile-1.0.aar",
          "size": 9563,
          "sha512": "5271304786759f31c13997410147e55f7fa2fb9bee2c1d3154225d450008ecaebc4b84720f12cf1a0898f553d858b68c206e1109190fc99f46913abebc2c17ad",
          "sha256": "2c4acffe5512ea9c5489e7a6fca713616ec3bd3631b21c056d10dae02d125829",
          "sha1": "f751428b836ba959e75616dfb61ec7a979ae3b72",
          "md5": "1e796a042704cb3adbc985efbf8afa88"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_profile-1.0.aar",
          "url": "device_info_plus_profile-1.0.aar",
          "size": 9563,
          "sha512": "5271304786759f31c13997410147e55f7fa2fb9bee2c1d3154225d450008ecaebc4b84720f12cf1a0898f553d858b68c206e1109190fc99f46913abebc2c17ad",
          "sha256": "2c4acffe5512ea9c5489e7a6fca713616ec3bd3631b21c056d10dae02d125829",
          "sha1": "f751428b836ba959e75616dfb61ec7a979ae3b72",
          "md5": "1e796a042704cb3adbc985efbf8afa88"
        }
      ]
    }
  ]
}
