{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_profile-1.0.aar",
          "url": "device_info_plus_profile-1.0.aar",
          "size": 9564,
          "sha512": "7b24fe64b0610dfc5a4b03fea78e129dce83e05f410e2cf3a426306ed58733d3755314d7a7345c77ab3f3e95242f7c028c7e8b6cccf1b11b6ce319b01f9d80e4",
          "sha256": "ff9d6c03bff75cea0c63fc1fb776ab36115b29eaab8b46db2646b8baa69753c7",
          "sha1": "4b1bdac50cbd0a097d61d3ab762c5154913ccd83",
          "md5": "2c0ee6b38d6a36b03e717b8441b60030"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_profile-1.0.aar",
          "url": "device_info_plus_profile-1.0.aar",
          "size": 9564,
          "sha512": "7b24fe64b0610dfc5a4b03fea78e129dce83e05f410e2cf3a426306ed58733d3755314d7a7345c77ab3f3e95242f7c028c7e8b6cccf1b11b6ce319b01f9d80e4",
          "sha256": "ff9d6c03bff75cea0c63fc1fb776ab36115b29eaab8b46db2646b8baa69753c7",
          "sha1": "4b1bdac50cbd0a097d61d3ab762c5154913ccd83",
          "md5": "2c0ee6b38d6a36b03e717b8441b60030"
        }
      ]
    }
  ]
}
