{
  "formatVersion": "1.1",
  "component": {
    "group": "com.crazecoder.openfile",
    "module": "open_filex_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "open_filex_release-1.0.aar",
          "url": "open_filex_release-1.0.aar",
          "size": 13771,
          "sha512": "069e4505cdd0454663ace45d9e94d01a6da0d88d4d9d3eac4dd9f6c660c8de57f86b3c345caf405874582553aaf4baa27175a05634a593662958906b5c4bb4c0",
          "sha256": "aacfc0bf0a06f1177515dcabc440d44ab4fedbf6509bb8b5f68e1a2a69955a84",
          "sha1": "b0d97427df8a78230adadd15534839d1ed62c59d",
          "md5": "426601c39e29807976c378513b08ced1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "open_filex_release-1.0.aar",
          "url": "open_filex_release-1.0.aar",
          "size": 13771,
          "sha512": "069e4505cdd0454663ace45d9e94d01a6da0d88d4d9d3eac4dd9f6c660c8de57f86b3c345caf405874582553aaf4baa27175a05634a593662958906b5c4bb4c0",
          "sha256": "aacfc0bf0a06f1177515dcabc440d44ab4fedbf6509bb8b5f68e1a2a69955a84",
          "sha1": "b0d97427df8a78230adadd15534839d1ed62c59d",
          "md5": "426601c39e29807976c378513b08ced1"
        }
      ]
    }
  ]
}
