{
  "formatVersion": "1.1",
  "component": {
    "group": "com.crazecoder.openfile",
    "module": "open_filex_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "open_filex_release-1.0.aar",
          "url": "open_filex_release-1.0.aar",
          "size": 13707,
          "sha512": "8d391402ba888ffafb607771443ff593617bf144b8cc206a2f1955e1890b358b933abe93637fb2ade9b0635d8ddcd1a6b31111749ab8b29e16c7fcea4fd270a4",
          "sha256": "9df199d5db0fb600ef42eaf934534594f281ec009764382f0f69c12e34c206ef",
          "sha1": "17e2112f2f471c415ce8acbca980a500d9110caa",
          "md5": "1bf51b2e1c51a619aa4850adc5380dfb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "open_filex_release-1.0.aar",
          "url": "open_filex_release-1.0.aar",
          "size": 13707,
          "sha512": "8d391402ba888ffafb607771443ff593617bf144b8cc206a2f1955e1890b358b933abe93637fb2ade9b0635d8ddcd1a6b31111749ab8b29e16c7fcea4fd270a4",
          "sha256": "9df199d5db0fb600ef42eaf934534594f281ec009764382f0f69c12e34c206ef",
          "sha1": "17e2112f2f471c415ce8acbca980a500d9110caa",
          "md5": "1bf51b2e1c51a619aa4850adc5380dfb"
        }
      ]
    }
  ]
}
