{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.videoplayer",
    "module": "video_player_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_debug-1.0.aar",
          "url": "video_player_android_debug-1.0.aar",
          "size": 41741,
          "sha512": "8df20e2507b022f0224373e25072234cdf6895aff89ed8f05b9243334ea6e12a22097f71e9433f9cb2bd7d2a865c1e0db21215292b07ad83af55021d1e34c9f4",
          "sha256": "57ba07e480960eb42ebc6a8e35dd24e9295b1e210caa6c169553d1cc3957b8fe",
          "sha1": "16540c1f13167800ec0e41ff0cf359c2e790c5a8",
          "md5": "545bec346acfa960fc69009d463d9aeb"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.4"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.18.4"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.18.4"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-smoothstreaming",
          "version": {
            "requires": "2.18.4"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_debug-1.0.aar",
          "url": "video_player_android_debug-1.0.aar",
          "size": 41741,
          "sha512": "8df20e2507b022f0224373e25072234cdf6895aff89ed8f05b9243334ea6e12a22097f71e9433f9cb2bd7d2a865c1e0db21215292b07ad83af55021d1e34c9f4",
          "sha256": "57ba07e480960eb42ebc6a8e35dd24e9295b1e210caa6c169553d1cc3957b8fe",
          "sha1": "16540c1f13167800ec0e41ff0cf359c2e790c5a8",
          "md5": "545bec346acfa960fc69009d463d9aeb"
        }
      ]
    }
  ]
}
