{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.videoplayer",
    "module": "video_player_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_debug-1.0.aar",
          "url": "video_player_android_debug-1.0.aar",
          "size": 42234,
          "sha512": "56fde0a66dccde411fdda5149993db84f2cee34092e655060d5da7b515fedb4c9ddbac3cd70097401339273fdcd5ae27f009a268c63fdecc1621730ce0eb905d",
          "sha256": "d0e1804d4862fe61f514142f3ed6d3cd71320ec8dec19dfaf33e946e2c8671e1",
          "sha1": "86ca2f5aa2dfc635ffb2056ac202cc958f60bf4b",
          "md5": "3db1cc964461a849407cf835fd9f28bf"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.4"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.18.4"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.18.4"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-smoothstreaming",
          "version": {
            "requires": "2.18.4"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_debug-1.0.aar",
          "url": "video_player_android_debug-1.0.aar",
          "size": 42234,
          "sha512": "56fde0a66dccde411fdda5149993db84f2cee34092e655060d5da7b515fedb4c9ddbac3cd70097401339273fdcd5ae27f009a268c63fdecc1621730ce0eb905d",
          "sha256": "d0e1804d4862fe61f514142f3ed6d3cd71320ec8dec19dfaf33e946e2c8671e1",
          "sha1": "86ca2f5aa2dfc635ffb2056ac202cc958f60bf4b",
          "md5": "3db1cc964461a849407cf835fd9f28bf"
        }
      ]
    }
  ]
}
