{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.videoplayer",
    "module": "video_player_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_release-1.0.aar",
          "url": "video_player_android_release-1.0.aar",
          "size": 40153,
          "sha512": "81179b44ed46fbff995335b16f66cc9ee09dbd2127d3b689e86d069b2f8483284c66be127401edf701409d22bc4635b9adc6b47446da45831260c013ce00baa0",
          "sha256": "2769cbfeffa26018bb5f003f122384fc4fbb20e5c884b875a83d2067b6d064b7",
          "sha1": "f0f5aac80880418385d1116d9a8c0e38932ba612",
          "md5": "2ac5de826c632c08f7d750c83ef38b4f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.4"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.18.4"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.18.4"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-smoothstreaming",
          "version": {
            "requires": "2.18.4"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_release-1.0.aar",
          "url": "video_player_android_release-1.0.aar",
          "size": 40153,
          "sha512": "81179b44ed46fbff995335b16f66cc9ee09dbd2127d3b689e86d069b2f8483284c66be127401edf701409d22bc4635b9adc6b47446da45831260c013ce00baa0",
          "sha256": "2769cbfeffa26018bb5f003f122384fc4fbb20e5c884b875a83d2067b6d064b7",
          "sha1": "f0f5aac80880418385d1116d9a8c0e38932ba612",
          "md5": "2ac5de826c632c08f7d750c83ef38b4f"
        }
      ]
    }
  ]
}
