{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.videoplayer",
    "module": "video_player_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_release-1.0.aar",
          "url": "video_player_android_release-1.0.aar",
          "size": 39723,
          "sha512": "5bdecd1f02acca02572bb84431fbc7294c764e8657211276020361c4f56906f7d58e26900f852f9e0252a8dee1e7a4493ff4fe72b971d0680d78499e8c66826f",
          "sha256": "725347564bc1720ce7b2254f89102c954ad08fe7f9076ed6ecfb07c08b6d3bae",
          "sha1": "fada0f21083bee131b5ecf23a8994753d0534fa0",
          "md5": "9f18cc550f23f6364661225573d9f4d7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.4"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.18.4"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.18.4"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-smoothstreaming",
          "version": {
            "requires": "2.18.4"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_release-1.0.aar",
          "url": "video_player_android_release-1.0.aar",
          "size": 39723,
          "sha512": "5bdecd1f02acca02572bb84431fbc7294c764e8657211276020361c4f56906f7d58e26900f852f9e0252a8dee1e7a4493ff4fe72b971d0680d78499e8c66826f",
          "sha256": "725347564bc1720ce7b2254f89102c954ad08fe7f9076ed6ecfb07c08b6d3bae",
          "sha1": "fada0f21083bee131b5ecf23a8994753d0534fa0",
          "md5": "9f18cc550f23f6364661225573d9f4d7"
        }
      ]
    }
  ]
}
