{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_profile-1.0.aar",
          "url": "permission_handler_android_profile-1.0.aar",
          "size": 25298,
          "sha512": "e0164c5923d744dc792853829ab26a56c4bf57fa4c0a01cbe6193606af9b8952396e34d0ba4e162925c243757a8ff88c9fbb1a20bada316863e4d53bef8f6683",
          "sha256": "6048f53fe9b22227f27a582ca0cd78c6732a09c0efd1c77c86b97498076a06ed",
          "sha1": "bd7451a2f53934794557c8140da4b842e79e7ca6",
          "md5": "137eb8514e9a42b2c87c4c6583d1aac4"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_profile-1.0.aar",
          "url": "permission_handler_android_profile-1.0.aar",
          "size": 25298,
          "sha512": "e0164c5923d744dc792853829ab26a56c4bf57fa4c0a01cbe6193606af9b8952396e34d0ba4e162925c243757a8ff88c9fbb1a20bada316863e4d53bef8f6683",
          "sha256": "6048f53fe9b22227f27a582ca0cd78c6732a09c0efd1c77c86b97498076a06ed",
          "sha1": "bd7451a2f53934794557c8140da4b842e79e7ca6",
          "md5": "137eb8514e9a42b2c87c4c6583d1aac4"
        }
      ]
    }
  ]
}
