{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_profile-1.0.aar",
          "url": "permission_handler_android_profile-1.0.aar",
          "size": 25039,
          "sha512": "a45c99020e58cdadf053995d9267219d57b466e1aaa6eeaffcbc16a0e5e90cbddc99fb481c10377ed39f2d4205957976d405cede883ded49819455cfbf8123c5",
          "sha256": "aaf40cff4ba5f24bd85c29bfb8126c017f5517391adc02a143fccc5e815fb9cf",
          "sha1": "44a8f96cea268d4593cd3f014374446c4dda725e",
          "md5": "dd5e795f8788d934ba5266a43dbd9add"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b24591ed328a2d4ce6505819e2f5898a78132f7f"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_profile-1.0.aar",
          "url": "permission_handler_android_profile-1.0.aar",
          "size": 25039,
          "sha512": "a45c99020e58cdadf053995d9267219d57b466e1aaa6eeaffcbc16a0e5e90cbddc99fb481c10377ed39f2d4205957976d405cede883ded49819455cfbf8123c5",
          "sha256": "aaf40cff4ba5f24bd85c29bfb8126c017f5517391adc02a143fccc5e815fb9cf",
          "sha1": "44a8f96cea268d4593cd3f014374446c4dda725e",
          "md5": "dd5e795f8788d934ba5266a43dbd9add"
        }
      ]
    }
  ]
}
