{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_profile-1.0.aar",
          "url": "permission_handler_android_profile-1.0.aar",
          "size": 25091,
          "sha512": "2c67df08774e9e92bc9d3fbee1e1c9891792e7526d11bb27d6aa474c83f6ef15f9fc3cb987cfb07708a67c38966f1bbfbd502fc1743ee20aff38487351f7c389",
          "sha256": "7595a43d3e30cae4414a1676af8deb970108974e28455968c1d61a6d7d9b5f81",
          "sha1": "908cd950cb2c8dd965d1b98a64dbef38d6adb6ea",
          "md5": "06a3c823ff5fafe610bbf53a73cb9423"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_profile-1.0.aar",
          "url": "permission_handler_android_profile-1.0.aar",
          "size": 25091,
          "sha512": "2c67df08774e9e92bc9d3fbee1e1c9891792e7526d11bb27d6aa474c83f6ef15f9fc3cb987cfb07708a67c38966f1bbfbd502fc1743ee20aff38487351f7c389",
          "sha256": "7595a43d3e30cae4414a1676af8deb970108974e28455968c1d61a6d7d9b5f81",
          "sha1": "908cd950cb2c8dd965d1b98a64dbef38d6adb6ea",
          "md5": "06a3c823ff5fafe610bbf53a73cb9423"
        }
      ]
    }
  ]
}
