{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mr.flutter.plugin.filepicker",
    "module": "file_picker_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_profile-1.0.aar",
          "url": "file_picker_profile-1.0.aar",
          "size": 27513,
          "sha512": "d5e87449212fb70e0cab224e9cc72d6baee2152a22501434163816897b9fa9bf3d41d525b44829f9e9b96e05465f43ad212499f0da02b98225efd9d1a92a2a43",
          "sha256": "10ef53cb8c71f396d573e6b22e7689ec2689430fed616c9f563d4c74b1a5de9c",
          "sha1": "eaeae2d667fbc7b3f563d9ec5f898b55c90ed4d9",
          "md5": "f469f057d88f035e62aeb5fbbbf36277"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_profile-1.0.aar",
          "url": "file_picker_profile-1.0.aar",
          "size": 27513,
          "sha512": "d5e87449212fb70e0cab224e9cc72d6baee2152a22501434163816897b9fa9bf3d41d525b44829f9e9b96e05465f43ad212499f0da02b98225efd9d1a92a2a43",
          "sha256": "10ef53cb8c71f396d573e6b22e7689ec2689430fed616c9f563d4c74b1a5de9c",
          "sha1": "eaeae2d667fbc7b3f563d9ec5f898b55c90ed4d9",
          "md5": "f469f057d88f035e62aeb5fbbbf36277"
        }
      ]
    }
  ]
}
