{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mr.flutter.plugin.filepicker",
    "module": "file_picker_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_profile-1.0.aar",
          "url": "file_picker_profile-1.0.aar",
          "size": 27840,
          "sha512": "f9d7a9e7d65d5cdc841fdc70b29b037f68c9043898cf449f922553a738192eba93d221b2274a650df72c21647bdd2392a8e4f4b86dc785fc7a1eecba60762997",
          "sha256": "2a447fecabd1ed0aa8e9b19d0afeab66895935622725f51e4b71e8f1d012740b",
          "sha1": "bcd51fc78d0ab232277a044415a4fe37711988b9",
          "md5": "f4dc596304628c03c7768ba39b094fbc"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_profile-1.0.aar",
          "url": "file_picker_profile-1.0.aar",
          "size": 27840,
          "sha512": "f9d7a9e7d65d5cdc841fdc70b29b037f68c9043898cf449f922553a738192eba93d221b2274a650df72c21647bdd2392a8e4f4b86dc785fc7a1eecba60762997",
          "sha256": "2a447fecabd1ed0aa8e9b19d0afeab66895935622725f51e4b71e8f1d012740b",
          "sha1": "bcd51fc78d0ab232277a044415a4fe37711988b9",
          "md5": "f4dc596304628c03c7768ba39b094fbc"
        }
      ]
    }
  ]
}
