{
  "formatVersion": "1.1",
  "component": {
    "group": "com.advoques.document_file_save_plus",
    "module": "document_file_save_plus_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "document_file_save_plus_debug-1.0.aar",
          "url": "document_file_save_plus_debug-1.0.aar",
          "size": 8357,
          "sha512": "439725b24c54ff778fe0b7a1872f0e0ca5ea9ef5159e537df995201a3e72ffb1b248492e5ce62177a08d27ed7af6c5a60bc2a1353278fddb1f5e4997518c8244",
          "sha256": "7b5d2ebbc6124a87c337774e90677d0c5c89ad12765d66f20e6341ecf22c0aac",
          "sha1": "4a9e7db453b761d0b99264fccc0eabf93809bdd4",
          "md5": "1d343629a946c8ad81b3f24e18de0bae"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "document_file_save_plus_debug-1.0.aar",
          "url": "document_file_save_plus_debug-1.0.aar",
          "size": 8357,
          "sha512": "439725b24c54ff778fe0b7a1872f0e0ca5ea9ef5159e537df995201a3e72ffb1b248492e5ce62177a08d27ed7af6c5a60bc2a1353278fddb1f5e4997518c8244",
          "sha256": "7b5d2ebbc6124a87c337774e90677d0c5c89ad12765d66f20e6341ecf22c0aac",
          "sha1": "4a9e7db453b761d0b99264fccc0eabf93809bdd4",
          "md5": "1d343629a946c8ad81b3f24e18de0bae"
        }
      ]
    }
  ]
}
