{
  "formatVersion": "1.1",
  "component": {
    "group": "com.advoques.document_file_save_plus",
    "module": "document_file_save_plus_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "document_file_save_plus_debug-1.0.aar",
          "url": "document_file_save_plus_debug-1.0.aar",
          "size": 8357,
          "sha512": "1d72594e150173a3484a65a4c1b3353f1af1600c0da809bdbd1eed86c160e0c34460227c8ad0d137b5ef1c0e93379bd31cc00d6b9b57ee24e9f4df2835eba5b2",
          "sha256": "89f8e940a5147c7007793cd0b897a0fd9bdb6b21c6804758ce1d43cb7f366c10",
          "sha1": "c38a3265db6568c54980e4ac4014a9ac0111226e",
          "md5": "ec00ad31b47e81d2ba20697c76ae44b7"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "document_file_save_plus_debug-1.0.aar",
          "url": "document_file_save_plus_debug-1.0.aar",
          "size": 8357,
          "sha512": "1d72594e150173a3484a65a4c1b3353f1af1600c0da809bdbd1eed86c160e0c34460227c8ad0d137b5ef1c0e93379bd31cc00d6b9b57ee24e9f4df2835eba5b2",
          "sha256": "89f8e940a5147c7007793cd0b897a0fd9bdb6b21c6804758ce1d43cb7f366c10",
          "sha1": "c38a3265db6568c54980e4ac4014a9ac0111226e",
          "md5": "ec00ad31b47e81d2ba20697c76ae44b7"
        }
      ]
    }
  ]
}
